In [2]:
import pandas as pd
from bs4 import BeautifulSoup
# pip install webcolors==1.3

In [3]:
def remove_html(text):
    try:
        soup = BeautifulSoup(text, 'lxml')
        html_free = soup.get_text(strip=True)
        return html_free
    except:
        return "missing"

Creat a function to clean a dataframe from the  scrape:

In [4]:
def EDA(df):
    # Remove html and strip off brackets and 'Color:' from color column
    df['color'] = df['color'].apply(lambda x: remove_html(x)).str.replace(']', '').str.replace('[', '').str.replace('Color:', '')
    
    # Replace escape characters and white space in Category column 
    df['category'] = df['category'].str.replace('\n', '').str.replace('  ', '')
    
    # Split Categroy column on the '›' symbol, up to 6 times and return them in a new df where each split is a new column 
    category = df['category'].str.split("›", n=6, expand=True)
    
    # Rename each category split column and add it onto the original df
    df['department'] = category[0]
    df['demographic'] = category[1]
    df['division'] = category[2]
    df['category'] = category[3]
    df['subcategory'] = category[4]
    df['type'] = category[5]
    df['detail_type'] = category[6]
    
    # Remove special characters from the description column 
    df['description'] = df['description'].str.replace('\t', '').str.replace('\n', '')
    
    # Remove html and strip off brackets from details column
    df['details'] = df['details'].apply(lambda x: remove_html(x)).str.replace(']', '').str.replace('[', '')
   
    #Remove html and cut off 'Size:' from the size column 
    df['size'] = df['size'].apply(lambda x: remove_html(x)).str.replace('Size:', '')
    
    return df.head()

In [5]:
df1 = pd.read_csv('data/product8000.csv', index_col=[0])

In [6]:
df1.head()

,asin,category,color,description,details,name,size
0,0000031887,Sports & Outdoors\n \n\n\n ...,unavailable,This fits your .\n \n\n\n Make sure this fi...,[],Mystiqueshapes Girls Ballet Tutu Neon Lime Green,NaN
1,0123456479,"Clothing, Shoes & Jewelry\n \n\n\n ...",unavailable,This fits your .\n \n\n\n Make sure this fi...,[],SHINING IMAGE HUGE PINK LEATHER JEWELRY BOX / ...,NaN
2,1608299953,Software\n \n\n\n ›\n ...,unavailable,Access for up to 5 family members\n\t\t\t\t\t\...,[],Learn French: Rosetta Stone French - Level 1,NaN
3,1617160377,Software\n \n\n\n ›\n ...,unavailable,Access for up to 5 family members\n\t\t\t\t\t\...,[],Learn Italian: Rosetta Stone Italian - Level 1,NaN
4,B00001W0KA,Toys & Games\n \n\n\n ›...,"<div class=""a-section a-spacing-small"" id=""var...",Lead Free\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\n \n\t...,[],Buzz Lightyear Boy's Deluxe Toy Story Costume,"<div class=""a-section a-spacing-base variation..."

In [7]:
df2 = pd.read_csv('data/product20000.csv', index_col=[0])
df2.head()

,asin,category,color,description,details,name,size
0,B006W71WJI,"Clothing, Shoes & Jewelry\n \n\n\n ...","<div class=""a-section a-spacing-small"" id=""var...",100% Leather\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\n \...,[],Dansko Women's Valerie Pull-Up Clog,"<div class=""a-section a-spacing-small"" id=""var..."
1,B006W8QR56,"Clothing, Shoes & Jewelry\n \n\n\n ...","<div class=""a-section a-spacing-small"" id=""var...",IDEAL SIZE -Drawstring backpacks come in one s...,[],Mato & Hash Drawstring Bulk Bags Cinch Sacks B...,"<div class=""a-section a-spacing-base variation..."
2,B006W8WLTW,"Clothing, Shoes & Jewelry\n \n\n\n ...","<div class=""a-section a-spacing-small"" id=""var...",100% Interlock Cotton\n\t\t\t\t\t\t\t\n\t\t\t\...,[],Luvable Friends Baby Sayings Bodysuit – Wild Boy,"<div class=""a-section a-spacing-small"" id=""var..."
3,B006W8WMP0,unknown category,unknown color,unknown details,NaN,unknown product name,NaN
4,B006WANIVK,"Clothing, Shoes & Jewelry\n \n\n\n ...","<div class=""a-section a-spacing-small"" id=""var...",90% Cotton | 10% Rayon\n\t\t\t\t\t\t\t\n\t\t\t...,[],Funfash Plus Size Women Open Angel Sleeve Cold...,"<div class=""a-section a-spacing-base variation..."

In [8]:
df3 = pd.read_csv('data/product21180.csv', index_col=[0])
df3.head()

,asin,category,color,description,details,name,size
0,B00B8ZJ8U4,"Clothing, Shoes & Jewelry\n \n\n\n ...",unavailable,THIS PRICE IS FOR TWO BRACELETS!\n\t\t\t\t\t\t...,"[<td class=""a-span7 a-size-base"">\n ...",JOTW 2 Pieces of Goldtone with Clear Iced Out ...,NaN
1,B00B93TTHM,"Clothing, Shoes & Jewelry\n \n\n\n ...","<div class=""a-section a-spacing-small"" id=""var...",100% Polyester\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\n...,[],Doublju Classic Slim Fit Sleeveless Sexy Bodyc...,"<div class=""a-section a-spacing-small"" id=""var..."
2,B00B93UDRW,"Clothing, Shoes & Jewelry\n \n\n\n ...","<div class=""a-section a-spacing-small"" id=""var...",65% Cotton / 35% Polyester\n\t\t\t\t\t\t\t\n\t...,[],Doublju Slim Fit Ribbed Knit Button Down Henle...,"<div class=""a-section a-spacing-small"" id=""var..."
3,B00B93W5R8,unknown category,unknown color,unknown details,NaN,unknown product name,NaN
4,B00B98MPWS,"Clothing, Shoes & Jewelry\n \n\n\n ...","<div class=""a-section a-spacing-small"" id=""var...",Synthetic\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\n \n\t...,[],Merrell Men's Ascend Glove Minimal Running Shoe,"<div class=""a-section a-spacing-base variation..."

In [9]:
df4 = pd.read_csv('data/product23033.csv', index_col=[0])
df4.head()

,asin,category,color,description,details,name,size
0,B00CWU9H9G,"Clothing, Shoes & Jewelry\n \n\n\n ...","<div class=""a-section a-spacing-small"" id=""var...",100% Rayon\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\n \n\...,[],Rayon Short Sleeves Flyaway Cardigan Shawl Col...,"<div class=""a-section a-spacing-small"" id=""var..."
1,B00CWUC9TQ,Sports & Outdoors\n \n\n\n ...,"<div class=""a-section a-spacing-small"" id=""var...",Imported\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\n \n\t\...,[],"Plus Size Yoga Long Stretch Pants 92% Cotton, ...","<div class=""a-section a-spacing-small"" id=""var..."
2,B00CWVE9KM,"Clothing, Shoes & Jewelry\n \n\n\n ...","<div class=""a-section a-spacing-small"" id=""var...","Scoop neck short sleeve top, super comfy Plus ...",[],Hollywood Star Fashion Women's Short Cap Sleev...,"<div class=""a-section a-spacing-base variation..."
3,B00CWVUVMC,"Clothing, Shoes & Jewelry\n \n\n\n ...",unavailable,"CLASSIC DESIGN: PU leather band, roman number ...","[<td class=""a-span7 a-size-base"">\n ...","Mens Quartz Watch, Roman Numeral Business Casu...",NaN
4,B00CWW1Q1Q,"Clothing, Shoes & Jewelry\n \n\n\n ...","<div class=""a-section a-spacing-small"" id=""var...",Chiffon Sheer Long Sleeves Blouse\n\t\t\t\t\t\...,[],Basic Long Sleeves Sheer Chiffon Blouse with P...,"<div class=""a-section a-spacing-small"" id=""var..."

In [10]:
# list of DataFrames to be concatonated
dataframes = [df1, df2, df3, df4]

# Concat all 4 DataFrames into one, along the row axis.
total_product = pd.concat(dataframes, axis=0)

In [11]:
total_product.shape

(17033, 7)

In [12]:
EDA(total_product)

,asin,category,color,description,details,name,size,department,demographic,division,subcategory,type,detail_type
0,0000031887,Dance,unavailable,This fits your . Make sure this fitsby ent...,,Mystiqueshapes Girls Ballet Tutu Neon Lime Green,missing,Sports & Outdoors,Sports & Fitness,Other Sports,Clothing,Girls,Skirts
1,0123456479,Jewelry Boxes & Organizers,unavailable,This fits your . Make sure this fitsby ent...,,SHINING IMAGE HUGE PINK LEATHER JEWELRY BOX / ...,missing,"Clothing, Shoes & Jewelry","Shoe, Jewelry & Watch Accessories",Jewelry Accessories,Jewelry Boxes,None,None
2,1608299953,None,unavailable,Access for up to 5 family members Download act...,,Learn French: Rosetta Stone French - Level 1,missing,Software,Education & Reference,Languages,None,None,None
3,1617160377,None,unavailable,Access for up to 5 family members Download act...,,Learn Italian: Rosetta Stone Italian - Level 1,missing,Software,Education & Reference,Languages,None,None,None
4,B00001W0KA,None,Buzz Lightyear,Lead Free Child (4-6 & 7-8) Includes: Bodysuit...,,Buzz Lightyear Boy's Deluxe Toy Story Costume,SelectM(3T-4T)3T-4TSmall (4-6)Medium (7-8)Medi...,Toys & Games,Dress Up & Pretend Play,Costumes,None,None,None

In [13]:
total_product.isnull().sum()

asin               0
category       12260
color              0
description        0
details            0
name               0
size               0
department         0
demographic    12009
division       12077
subcategory    13867
type           16054
detail_type    16619
dtype: int64

In [14]:
total_product['department'].value_counts(dropna=False)

unknown category              12009
Clothing, Shoes & Jewelry      4690
Sports & Outdoors               226
Toys & Games                     36
Health & Household               18
Arts, Crafts & Sewing            13
Beauty & Personal Care           10
Electronics                       8
Home & Kitchen                    7
Tools & Home Improvement          6
Baby Products                     5
Software                          2
Purchase Circles                  1
Automotive                        1
Office Products                   1
Name: department, dtype: int64

In [15]:
robot_free_df = (total_product[total_product['department'] != 'unknown category'])

In [16]:
robot_free_df.shape

(5024, 13)

In [17]:
robot_free_df.dtypes

asin           object
category       object
color          object
description    object
details        object
name           object
size           object
department     object
demographic    object
division       object
subcategory    object
type           object
detail_type    object
dtype: object

In [18]:
robot_free_df.isnull().sum()

asin              0
category        251
color             0
description       0
details           0
name              0
size              0
department        0
demographic       0
division         68
subcategory    1858
type           4045
detail_type    4610
dtype: int64

In [19]:
norobotdf = pd.read_csv('data/product14000.csv', index_col=[0])
print(norobotdf.shape)
norobotdf.head()

(5466, 7)

,asin,category,color,description,details,name,size
0,B003ZVQQVS,"Clothing, Shoes & Jewelry\n \n\n\n ...",unavailable,This fits your .\n \n\n\n Make sure this fi...,[],High Sierra A.T. Ultimate Access Carry-On Whee...,NaN
1,B003ZVZDKS,"Clothing, Shoes & Jewelry\n \n\n\n ...","<div class=""a-section a-spacing-small"" id=""var...",90% cotton 10% polyester\n\t\t\t\t\t\t\t\n\t\t...,[],Champion Women's Favorite V-Neck Tee,"<div class=""a-section a-spacing-base variation..."
2,B003ZVZH5E,"Clothing, Shoes & Jewelry\n \n\n\n ...","<div class=""a-section a-spacing-small"" id=""var...",100% Cotton\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\n \n...,[],Champion Women's Favorite V-Neck Tank,"<div class=""a-section a-spacing-base variation..."
3,B003ZW0X2K,Sports & Outdoors\n \n\n\n ...,"<div class=""a-section a-spacing-small"" id=""var...",100% Polyester\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\n...,[],Champion Women's Absolute Workout Pant Short L...,"<div class=""a-section a-spacing-small"" id=""var..."
4,B003ZW163K,"Clothing, Shoes & Jewelry\n \n\n\n ...","<div class=""a-section a-spacing-small"" id=""var...",100% Cotton\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\n \n...,[],Champion Women's Favorite Short,"<div class=""a-section a-spacing-base variation..."

In [20]:
EDA(norobotdf)

,asin,category,color,description,details,name,size,department,demographic,division,subcategory,type,detail_type
0,B003ZVQQVS,None,unavailable,This fits your . Make sure this fitsby ent...,,High Sierra A.T. Ultimate Access Carry-On Whee...,missing,"Clothing, Shoes & Jewelry",Luggage & Travel Gear,Backpacks,None,None,None
1,B003ZVZDKS,Active,Oxford Gray,90% cotton 10% polyester Imported Not applicab...,,Champion Women's Favorite V-Neck Tee,SelectX-SmallSmallMediumLargeX-LargeXX-LargeSe...,"Clothing, Shoes & Jewelry",Women,Clothing,Active Shirts & Tees,None,None
2,B003ZVZH5E,"Tops, Tees & Blouses",White,100% Cotton Imported tank-top-and-cami-shirts ...,,Champion Women's Favorite V-Neck Tank,SelectSmallMediumLargeX-LargeXX-LargeSelectif(...,"Clothing, Shoes & Jewelry",Women,Clothing,Tanks & Camis,None,None
3,B003ZW0X2K,Yoga,Black,100% Polyester pants closure Silky performance...,,Champion Women's Absolute Workout Pant Short L...,Small,Sports & Outdoors,Sports & Fitness,Exercise & Fitness,Clothing,Women,Pants
4,B003ZW163K,Active,Oxford Gray,100% Cotton Imported shorts closure Machine wa...,,Champion Women's Favorite Short,SelectSmallLargeX-LargeSelectif(typeof(Twister...,"Clothing, Shoes & Jewelry",Women,Clothing,Active Shorts,None,None

In [21]:
norobotdf2 = pd.read_csv('data/product8534.csv', index_col=[0])
print(norobotdf2.shape)
norobotdf2.head()

(534, 7)

,asin,category,color,description,details,name,size
0,B003QOJB3O,"Clothing, Shoes & Jewelry\n \n\n\n ...","<div class=""a-section a-spacing-small"" id=""var...",100% polyster\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\n ...,[],Sport-Tek Women's Side Blocked Performance Pol...,"<div class=""a-section a-spacing-base variation..."
1,B003QORIMA,"Clothing, Shoes & Jewelry\n \n\n\n ...","<div class=""a-section a-spacing-base variation...",Cotton & Polyester\n\t\t\t\t\t\t\t\n\t\t\t\t\t...,[],Port Authority® Ladies Silk Touch™ Polo. L500,"<div class=""a-section a-spacing-base variation..."
2,B003QOZ732,unknown category,unknown color,unknown details,NaN,unknown product name,NaN
3,B003QSIMRQ,"Clothing, Shoes & Jewelry\n \n\n\n ...","<div class=""a-section a-spacing-small"" id=""var...",100% Polyester\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\n...,[],eVogues Women's Sexy O-Ring Necklace Sleeveles...,"<div class=""a-section a-spacing-small"" id=""var..."
4,B003QSVLWE,"Clothing, Shoes & Jewelry\n \n\n\n ...","<div class=""a-section a-spacing-small"" id=""var...",These soft and comfortable flannel pajamas hav...,[],Men's Flannel Pajamas,"<div class=""a-section a-spacing-base variation..."

In [22]:
EDA(norobotdf2)

,asin,category,color,description,details,name,size,department,demographic,division,subcategory,type,detail_type
0,B003QOJB3O,"Tops, Tees & Blouses",Light Pink/White,"100% polyster Button closure 3.8-ounce, 100% p...",,Sport-Tek Women's Side Blocked Performance Pol...,SelectX-SmallSmallMediumLargeX-LargeXX-Large3X...,"Clothing, Shoes & Jewelry",Women,Clothing,Polos,None,None
1,B003QORIMA,"Tops, Tees & Blouses",Deep BerryRedTropical PinkSunflower YellowTurq...,Cotton & Polyester Button closure An enduring ...,,Port Authority® Ladies Silk Touch™ Polo. L500,SelectXSX-SmallSSmallMMediumLLargeX-LargeXX-La...,"Clothing, Shoes & Jewelry",Women,Clothing,Polos,None,None
2,B003QOZ732,None,unknown color,unknown details,missing,unknown product name,missing,unknown category,None,None,None,None,None
3,B003QSIMRQ,"Tops, Tees & Blouses",Black,"100% Polyester Made in USA 1XL=Size 13/14, 2XL...",,eVogues Women's Sexy O-Ring Necklace Sleeveles...,2X,"Clothing, Shoes & Jewelry",Women,Clothing,Tanks & Camis,None,None
4,B003QSVLWE,Sleep & Lounge,Black,These soft and comfortable flannel pajamas hav...,,Men's Flannel Pajamas,SelectSmallMediumExtra Large (2X)Extra Large (...,"Clothing, Shoes & Jewelry",Men,Clothing,Sleep Sets,None,None

In [23]:
norobotdf3 = pd.read_csv('data/redo1.csv', index_col=[0])
print(norobotdf3.shape)
norobotdf3.head()

(598, 13)

,asin,category,color,description,details,name,size,department,demographic,division,subcategory,type,detail_type
177,B000H6AQ0Q,Women,unavailable,This fits your . Make sure this fitsby ent...,missing,Timex 1440 Sports Digital Mid Size Black/Pink,missing,Sports & Outdoors,Outdoor Recreation,Outdoor Clothing,Accessories,Sport Watches,NaN
178,B000H6BYI4,Jewelry Boxes & Organizers,unavailable,This fits your . Make sure this fitsby ent...,missing,Caddy Bay Collection Wide Slot Jewelry Ring Di...,missing,"Clothing, Shoes & Jewelry","Shoe, Jewelry & Watch Accessories",Jewelry Accessories,Jewelry Boxes,NaN,NaN
179,B000H6DWZC,Jewelry Boxes & Organizers,unavailable,This fits your . Make sure this fitsby ent...,missing,Fairy Tale Jewelry Box,missing,"Clothing, Shoes & Jewelry","Shoe, Jewelry & Watch Accessories",Jewelry Accessories,Jewelry Boxes,NaN,NaN
180,B000H703V2,Oxfords,missing,"100% Full-grain leather,Leather,Nubuck Importe...",missing,Ecco Men's Track II Low GORE-TEX waterproof ou...,missing,"Clothing, Shoes & Jewelry",Men,Shoes,NaN,NaN,NaN
181,B000H7YCE6,"Bags, Cases & Sleeves",missing,This fits your . Make sure this fitsby ent...,missing,High Sierra Loop Backpack,missing,Electronics,Computers & Accessories,Laptop Accessories,Backpacks,NaN,NaN

In [24]:
norobotdf.shape

(5466, 13)

In [25]:
norobotdf2.shape

(534, 13)

In [26]:
clean_dfs = [robot_free_df, norobotdf, norobotdf2, norobotdf3]
robot_free_df = pd.concat(clean_dfs, axis=0)
robot_free_df.shape

(11622, 13)

In [27]:
robot_free_df.to_csv('robot_free.csv')

In [28]:
robot_free_df.isnull().mean()

asin           0.000000
category       0.143177
color          0.000000
description    0.000000
details        0.000000
name           0.000000
size           0.000000
department     0.000000
demographic    0.099897
division       0.111427
subcategory    0.419033
type           0.815953
detail_type    0.919721
dtype: float64

In [29]:
robot_free_df = pd.read_csv('data/robot_free.csv', index_col=[0])

In [30]:
robot_free_df.head()

,Unnamed: 0.1,asin,category,color,description,details,name,size,department,demographic,division,subcategory,type,detail_type
0,0,0000031887,Dance,unavailable,This fits your . Make sure this fitsby ent...,NaN,Mystiqueshapes Girls Ballet Tutu Neon Lime Green,missing,Sports & Outdoors,Sports & Fitness,Other Sports,Clothing,Girls,Skirts
1,1,0123456479,Jewelry Boxes & Organizers,unavailable,This fits your . Make sure this fitsby ent...,NaN,SHINING IMAGE HUGE PINK LEATHER JEWELRY BOX / ...,missing,"Clothing, Shoes & Jewelry","Shoe, Jewelry & Watch Accessories",Jewelry Accessories,Jewelry Boxes,NaN,NaN
2,2,1608299953,NaN,unavailable,Access for up to 5 family members Download act...,NaN,Learn French: Rosetta Stone French - Level 1,missing,Software,Education & Reference,Languages,NaN,NaN,NaN
3,3,1617160377,NaN,unavailable,Access for up to 5 family members Download act...,NaN,Learn Italian: Rosetta Stone Italian - Level 1,missing,Software,Education & Reference,Languages,NaN,NaN,NaN
4,4,B00001W0KA,NaN,Buzz Lightyear,Lead Free Child (4-6 & 7-8) Includes: Bodysuit...,NaN,Buzz Lightyear Boy's Deluxe Toy Story Costume,SelectM(3T-4T)3T-4TSmall (4-6)Medium (7-8)Medi...,Toys & Games,Dress Up & Pretend Play,Costumes,NaN,NaN,NaN

In [31]:
redo2 = pd.read_csv('data/redo2.csv', index_col=[0])
redo3 = pd.read_csv('data/redo3.csv', index_col=[0])
redo4 = pd.read_csv('data/redo4.csv', index_col=[0])
redo5 = pd.read_csv('data/redo5.csv', index_col=[0])
redo6 = pd.read_csv('data/redo6.csv', index_col=[0])

In [32]:
redo_dfs = [robot_free_df, redo2, redo3, redo4, redo5, redo6]

In [33]:
robot_free_df6 = pd.concat(redo_dfs, axis=0, sort=True, ignore_index=True)
robot_free_df6.shape

(17843, 14)

In [34]:
robot_free_df6.drop(columns='Unnamed: 0.1', inplace=True)

In [35]:
robot_free_df6.to_csv('data/robot_free6.csv', index=False)

In [36]:
robot_free_df6.head()

,asin,category,color,demographic,department,description,detail_type,details,division,name,size,subcategory,type
0,0000031887,Dance,unavailable,Sports & Fitness,Sports & Outdoors,This fits your . Make sure this fitsby ent...,Skirts,NaN,Other Sports,Mystiqueshapes Girls Ballet Tutu Neon Lime Green,missing,Clothing,Girls
1,0123456479,Jewelry Boxes & Organizers,unavailable,"Shoe, Jewelry & Watch Accessories","Clothing, Shoes & Jewelry",This fits your . Make sure this fitsby ent...,NaN,NaN,Jewelry Accessories,SHINING IMAGE HUGE PINK LEATHER JEWELRY BOX / ...,missing,Jewelry Boxes,NaN
2,1608299953,NaN,unavailable,Education & Reference,Software,Access for up to 5 family members Download act...,NaN,NaN,Languages,Learn French: Rosetta Stone French - Level 1,missing,NaN,NaN
3,1617160377,NaN,unavailable,Education & Reference,Software,Access for up to 5 family members Download act...,NaN,NaN,Languages,Learn Italian: Rosetta Stone Italian - Level 1,missing,NaN,NaN
4,B00001W0KA,NaN,Buzz Lightyear,Dress Up & Pretend Play,Toys & Games,Lead Free Child (4-6 & 7-8) Includes: Bodysuit...,NaN,NaN,Costumes,Buzz Lightyear Boy's Deluxe Toy Story Costume,SelectM(3T-4T)3T-4TSmall (4-6)Medium (7-8)Medi...,NaN,NaN

In [37]:
redo7 = pd.read_csv('data/redo7.csv', index_col=[0])
redo7.head()

          asin                                               name
0   B007WA2TCS  Allegra K Women V Neck Sleeveless Striped Pane...
2   B007WA2VB2  Allegra K Women Scoop Neck Drawstring Mid-Calf...
3   B007WA2ZTA  Allegra K Women Peter Pan 3/4 Sleeve Summer To...
4   B007WA3558  Allegra K Lady Ruffle Tie Neck Short Sleeves B...
10  B007WA3GMK  Allegra K Women Sweet Layered Tiered Crochet D...

In [41]:
final_df = pd.concat([robot_free_df6, redo7], sort=True).fillna(0)

In [42]:
final_df.head()

,asin,category,color,demographic,department,description,detail_type,details,division,name,size,subcategory,type
0,0000031887,Dance,unavailable,Sports & Fitness,Sports & Outdoors,This fits your . Make sure this fitsby ent...,Skirts,0,Other Sports,Mystiqueshapes Girls Ballet Tutu Neon Lime Green,missing,Clothing,Girls
1,0123456479,Jewelry Boxes & Organizers,unavailable,"Shoe, Jewelry & Watch Accessories","Clothing, Shoes & Jewelry",This fits your . Make sure this fitsby ent...,0,0,Jewelry Accessories,SHINING IMAGE HUGE PINK LEATHER JEWELRY BOX / ...,missing,Jewelry Boxes,0
2,1608299953,0,unavailable,Education & Reference,Software,Access for up to 5 family members Download act...,0,0,Languages,Learn French: Rosetta Stone French - Level 1,missing,0,0
3,1617160377,0,unavailable,Education & Reference,Software,Access for up to 5 family members Download act...,0,0,Languages,Learn Italian: Rosetta Stone Italian - Level 1,missing,0,0
4,B00001W0KA,0,Buzz Lightyear,Dress Up & Pretend Play,Toys & Games,Lead Free Child (4-6 & 7-8) Includes: Bodysuit...,0,0,Costumes,Buzz Lightyear Boy's Deluxe Toy Story Costume,SelectM(3T-4T)3T-4TSmall (4-6)Medium (7-8)Medi...,0,0

In [45]:
final_df.shape

(19766, 13)

In [44]:
final_df['name'].value_counts()

unknown product name                                                                                                                1161
Birkenstock Women's Mayari Birko-Flor Sandal                                                                                           7
MG Low Profile Dyed Cotton Twill Cap                                                                                                   7
DELSEY Paris Helium Aero Hardside Luggage with Spinner Wheels                                                                          6
Hanes Ultimate Men's 4-Pack Boxer Brief                                                                                                6
ASICS Women's GEL-Noosa Tri 8 Running Shoe                                                                                             6
Simple Leverback Round Gemstone Bead Ball Drop Earrings For Women For Teen 925 Sterling Silver More Birthstone                         6
Simple 6MM Gemstone Round Ball Stud Earrings For Women For Teen 925 Sterling Silver 9 Birthstones More Colors                          6
Fruit of the Loom Men's Pocket Crew Neck T-Shirt (Pack Of 4)                                                                           6
Carhartt Men's Signature Casual Belt                                                                                                   6
ASICS Men's GEL-Noosa Tri 8 Running Shoe                                                                                               6
Reebok Women's Easytone                                                                                                                6
Wrangler Men's Genuine Regular-Fit Jean                                                                                                5
uiphgjwexzv                                                                                                                            5
Allegra K Women's Off Shoulder Self Tie Bowknot Colorblock Casual Tunic Shirt                                                          5
Simple 8MM Gemstone Round Ball Stud Earrings For Women For Teen 925 Sterling Silver 9 Birthstone More Colors                           5
Timex Ironman Classic 30 Mid-Size Watch                                                                                                5
Sterling Silver 8mm Round Earrings                                                                                                     4
Nine West Women's Rocha Pump                                                                                                           4
Merrell Men's Bare Access 2 Minimal Trail Running Shoe                                                                                 4
EZsizer Ring Size Reducer, Ring Guard, Ring Size Adjuster Size: Mixed, 1 Narrow, 1 Medium, 1 Wide, for rings 0.5 mm-6.0 mm wide.       4
Champion Men's Jersey Muscle T-Shirt                                                                                                   4
Dansko Women's Professional Mule                                                                                                       4
Top Moda Women's COCO 1 Knee High Riding Boot                                                                                          4
Fruit of Loom Men's A-Shirt Multipack                                                                                                  4
Madden Girl Women's Getta Pump                                                                                                         4
Metal Factory Sterling Silver Crystal Ball Bead Charm Fits Pandora Chamilia Biagi Trollbeads European Bracelet                         4
Saucony Women's Cohesion 6 Running Shoe                                                                                                4
Levi's Boys' 550 Relaxed Fit Jeans                                                                                                     4
Travelon ID and Boarding Pass Holder , Black, One Size                                                                                 4
                                                                                                                                    ...
Levi's Men's 511 Slim Fit Jeans                                                                                                        1
Ladies' Ploy Urethane Leather Shoulder Bag/ Envelope Case (Model: B010280) (Brown)                                                     1
LifeStride Women's Wrangler Knee-High Boot                                                                                             1
Key Apparel Men's Enzyme Washed Denim 5-Pocket Jean                                                                                    1
New Balance Men's MT1010v2 Minimus Trail Running Shoe                                                                                  1
Up2date Fashion Women's Print Caftan, One Size, Style#Caf-18                                                                           1
Doctor Who Tardis in Space Junior's T-Shirt                                                                                            1
Ian and Valeri Co. Amber Sterling Silver Millennium Collection Spherical Contemporary Pendant Cube                                     1
Beads Hunter Silver Core Let It Snow! Snowflakes Glass Bead Charm                                                                      1
Simplicity Women's Summer Foldable Wide Brim Beach Straw Sun Visor Hats                                                                1
KEEN Women's Sterling City Lace Shoe                                                                                                   1
Starbay Sunville Infants Aqua Shoes For Water Sandals Aqua Socks                                                                       1
Casio Men's MQ24-9B Classic Analog Watch                                                                                               1
Nine West Women's Curri Sandal                                                                                                         1
OVALBUY Ox Bone Carved Elephant Pendant Necklace                                                                                       1
Crocs Men's Hover  Sneaker                                                                                                             1
Sterling Silver and 14k Rose Gold Diamond Accent Triple Heart Pendant Necklace,18"                                                     1
Alilang Vintage Inspired Flower Dragonfly Blue Bangle Cuff Bracelet                                                                    1
Rhode Island Novelty Kids Monarch Butterfly Plush Wings One Per Order                                                                  1
Minnetonka  Women's El Paso II Moccasin                                                                                                1
Carhartt Men's Sherpa Lined Sandstone Hooded Multi Pocket Jacket J284                                                                  1
Carhartt Women's Snap Front Plaid Cotton Shirt                                                                                         1
SUMMIT COLLECTION Art Nouveau Kneeling Fairy Jewelry Box with Dragonfly and Blooming Flower Decorations                                1
Reebok Women's ZigLite Electrify Running Shoe                                                                                          1
Bulova Men's 98C62  Marine Star Analog Japanese quartz Silver Watch                                                                    1
Carhartt Women's Norfolk Three Quarter Sleeve Slub Henley                                                                              1
Mato & Hash Military Shemagh Tactical 100% Cotton Scarf Head Wrap                                                                      1
FitwearUSA Women's Capri Legging                                                                                                       1
Levi's Women's 524 Skinny Bootcut Jeans                                                                                                1
Stacy Adams Men's Brisbane Sandal                                                                                                      1
Name: name, Length: 15244, dtype: int64

In [43]:
final_df[final_df['name'] == 'unknown ']

,asin,category,color,demographic,department,description,detail_type,details,division,name,size,subcategory,type
3786,B00KKXCJQU,0,0,0,0,0,0,0,0,Shacke Pak - 4 Set Packing Cubes - Travel Orga...,0,0,0

In [46]:
final_df['asin'].value_counts()

B007P76QF4    2
B001H0FE2G    2
B0083QLPYI    2
B008H2ET1E    2
B001CZYC9M    2
B002ABINW4    2
B007MS25NS    2
B001V80A96    2
B0032N1VZK    2
B001E5X2IM    2
B0088VSV0Y    2
B008KLORBE    2
B00AR2B91U    2
B001GUKPGC    2
B003OCY0YI    2
B00307RY0Y    2
B003HIBYRK    2
B0085IPO5A    2
B007UMD9GS    2
B0083M2DR0    2
B003QFZZRO    2
B008D6ONV0    2
B0085RY4SO    2
B001AMHIK2    2
B008R6M7QY    2
B007JVBGZG    2
B002SSUQF6    2
B0099XP220    2
B0085A491I    2
B001JQLOWW    2
             ..
B0032EXYFY    1
B004WYZI7K    1
B00DQYOMJ2    1
B00847TBRY    1
B008AEDVTU    1
B004GEASW6    1
B004HF79LC    1
B00CM27DDQ    1
B00FLTFITS    1
B00008ID0L    1
B000HKNAB4    1
B003R6P3EM    1
B0058Z0DG8    1
B00DDPFG3K    1
B00ABS67T4    1
B005WUHVLO    1
B004KK63UC    1
B009B4YR78    1
B0074BVAUW    1
B0006AAS5G    1
B008Z844II    1
B000UWJKXQ    1
B00B08JNXG    1
B006JOO3NG    1
B00BZHZ30Y    1
B00F3AWAJ6    1
B00962GYOY    1
B0045KFBSM    1
B004TUPO9Y    1
B007T4WT4U    1
Name: asin, Length: 16816, dtype: int64

In [50]:
final_df.drop_duplicates(inplace=True)

In [51]:
final_df.shape

(16816, 13)

In [52]:
final_df.to_csv('data/final_df.csv')