## Feature Engineering with NLTK  
_By: Rachel Koenig_ 
____

Imports

In [1]:
#Import pandas 
import pandas as pd
#Import Natual Language Toolkit
import nltk
#Import Beautiful Soup
from bs4 import BeautifulSoup   
#Import string for list of punctuation
import string
# Import the stop word list
from nltk.corpus import stopwords 
# Import Tokenizer
from nltk.tokenize import RegexpTokenizer
#Import Lemmatizer
from nltk.stem import WordNetLemmatizer
# Import stemmer.
from nltk.stem.porter import PorterStemmer

Read in csv.

In [2]:
df = pd.read_csv('data/reviews_and_products.csv', index_col=[0], low_memory=False)

In [3]:
#check first 5 rows 
df.head()

,reviewerID,asin,reviewText,overall,summary,unixReviewTime,review_date,color,description,details,...,Tops_Tees,Trunks,Umbrellas,Underwear,Wallets,Wear_to_Work,Wrist_Watches,Arm_Warmers,Baseball_Caps,Berets
0,A1KLRMWW2FWPL4,0000031887,This is a great tutu and at a really great pri...,5.0,Great tutu- not cheaply made,1297468800,2011-02-12,unavailable,This fits your . Make sure this fitsby ent...,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,A2G5TCU2WDFZ65,0000031887,I bought this for my 4 yr old daughter for dan...,5.0,Very Cute!!,1358553600,2013-01-19,unavailable,This fits your . Make sure this fitsby ent...,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,A1RLQXYNCMWRWN,0000031887,What can I say... my daughters have it in oran...,5.0,I have buy more than one,1357257600,2013-01-04,unavailable,This fits your . Make sure this fitsby ent...,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,A8U3FAMSJVHS5,0000031887,"We bought several tutus at once, and they are ...",5.0,"Adorable, Sturdy",1398556800,2014-04-27,unavailable,This fits your . Make sure this fitsby ent...,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,A3GEOILWLK86XM,0000031887,Thank you Halo Heaven great product for Little...,5.0,Grammy's Angels Love it,1394841600,2014-03-15,unavailable,This fits your . Make sure this fitsby ent...,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
# Check data types 
df.dtypes.head(15)

reviewerID             object
asin                   object
reviewText             object
overall               float64
summary                object
unixReviewTime          int64
review_date            object
color                  object
description            object
details                object
name                   object
size                   object
Arts_Crafts_Sewing    float64
Automotive            float64
Baby_Products         float64
dtype: object

In [5]:
#Check column names 
df.columns

Index(['reviewerID', 'asin', 'reviewText', 'overall', 'summary',
       'unixReviewTime', 'review_date', 'color', 'description', 'details',
       ...
       'Tops_Tees', 'Trunks', 'Umbrellas', 'Underwear', 'Wallets',
       'Wear_to_Work', 'Wrist_Watches', 'Arm_Warmers', 'Baseball_Caps',
       'Berets'],
      dtype='object', length=823)

Check size of DataFrame: 168,995 rows, of different products and reviewers.

In [6]:
df.shape

(168995, 823)

In [7]:
#Check for nulls 
df.isnull().sum().head(25)

reviewerID                  0
asin                        0
reviewText                 16
overall                     0
summary                     1
unixReviewTime              0
review_date                 0
color                       0
description                 0
details                     0
name                        0
size                        0
Arts_Crafts_Sewing          0
Automotive                  0
Baby_Products               0
Beauty_Personal_Care        0
Cell_Phones_Accessories     0
Clothing_Shoes_Jewelry      0
Electronics                 0
Health_Household            0
Home_Kitchen                0
Industrial_Scientific       0
Office_Products             0
Purchase_Circles            0
Software                    0
dtype: int64

Fill nulls with the string `'none'`

In [8]:
df.fillna('none', inplace=True)

In [9]:
df.isnull().sum().sum()

0

Create a new DataFrame called `users` that includes all features except `reviewText`, `summary`, `unixReviewTime`, `review_date`, `description`, `details`, and `size`

In [10]:
users = df.drop(columns=['reviewText', 'summary', 'unixReviewTime', 
                 'review_date', 'description', 'details', 'size'])
users.head()

,reviewerID,asin,overall,color,name,Arts_Crafts_Sewing,Automotive,Baby_Products,Beauty_Personal_Care,Cell_Phones_Accessories,...,Tops_Tees,Trunks,Umbrellas,Underwear,Wallets,Wear_to_Work,Wrist_Watches,Arm_Warmers,Baseball_Caps,Berets
0,A1KLRMWW2FWPL4,0000031887,5.0,unavailable,Mystiqueshapes Girls Ballet Tutu Neon Lime Green,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,A2G5TCU2WDFZ65,0000031887,5.0,unavailable,Mystiqueshapes Girls Ballet Tutu Neon Lime Green,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,A1RLQXYNCMWRWN,0000031887,5.0,unavailable,Mystiqueshapes Girls Ballet Tutu Neon Lime Green,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,A8U3FAMSJVHS5,0000031887,5.0,unavailable,Mystiqueshapes Girls Ballet Tutu Neon Lime Green,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,A3GEOILWLK86XM,0000031887,5.0,unavailable,Mystiqueshapes Girls Ballet Tutu Neon Lime Green,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Group the rest of the columns based on `reviewerID` column using the groupby function.

In [11]:
users_cats = users.groupby(['reviewerID']).sum().iloc[:, 2:]  # Sum up all categories that a user has purchased 
users_cats.head(3)

,Automotive,Baby_Products,Beauty_Personal_Care,Cell_Phones_Accessories,Clothing_Shoes_Jewelry,Electronics,Health_Household,Home_Kitchen,Industrial_Scientific,Office_Products,...,Tops_Tees,Trunks,Umbrellas,Underwear,Wallets,Wear_to_Work,Wrist_Watches,Arm_Warmers,Baseball_Caps,Berets
reviewerID,,,,,,,,,,,,,,,,,,,,,
A001114613O3F18Q5NVR6,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A00146182PNM90WNNAZ5Q,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A00338282E99B8OR2JYTZ,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Check the output for one reviewerID to make sure there are some values higher than one, proving the above function worked.

In [12]:
user1 = users_cats.loc['A001114613O3F18Q5NVR6'].to_dict() 
{k:v for k,v in user1.items() if v != 0}

{'Clothing_Shoes_Jewelry': 4.0,
 'Sports_Outdoors': 1.0,
 'Novelty_More': 1.0,
 'Sports_Fitness': 1.0,
 'Novelty': 1.0,
 'Exercise_Fitness': 1.0,
 'Casual': 1.0,
 'Leggings': 1.0,
 'Men': 2.0,
 'Shorts': 1.0,
 'Skirts': 1.0,
 'T-Shirts': 1.0,
 'Women': 2.0,
 'Clothing': 4.0,
 'Shoes': 1.0,
 'Fashion_Sneakers': 1.0,
 'Running': 1.0}

In [13]:
num_reviews = users.groupby(['reviewerID']).count()['asin']  # Count up how many asins are related to each user.

In [14]:
users['number_of_reviews'] = users['reviewerID'].map(num_reviews)  # Create a new column for each user's total number of reviews
users['number_of_reviews'].head()

0    3
1    6
2    5
3    7
4    4
Name: number_of_reviews, dtype: int64

In [15]:
user_stars = users.groupby(['reviewerID']).mean().round(2)['overall'] # Find the average number of stars each user rates

users['average_stars_given'] = users['reviewerID'].map(user_stars)  # Create a new column for the users' average rating
users['average_stars_given'].head()

0    5.00
1    4.17
2    4.20
3    4.00
4    4.50
Name: average_stars_given, dtype: float64

In [16]:
users.head()

,reviewerID,asin,overall,color,name,Arts_Crafts_Sewing,Automotive,Baby_Products,Beauty_Personal_Care,Cell_Phones_Accessories,...,Umbrellas,Underwear,Wallets,Wear_to_Work,Wrist_Watches,Arm_Warmers,Baseball_Caps,Berets,number_of_reviews,average_stars_given
0,A1KLRMWW2FWPL4,0000031887,5.0,unavailable,Mystiqueshapes Girls Ballet Tutu Neon Lime Green,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3,5.00
1,A2G5TCU2WDFZ65,0000031887,5.0,unavailable,Mystiqueshapes Girls Ballet Tutu Neon Lime Green,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6,4.17
2,A1RLQXYNCMWRWN,0000031887,5.0,unavailable,Mystiqueshapes Girls Ballet Tutu Neon Lime Green,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5,4.20
3,A8U3FAMSJVHS5,0000031887,5.0,unavailable,Mystiqueshapes Girls Ballet Tutu Neon Lime Green,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7,4.00
4,A3GEOILWLK86XM,0000031887,5.0,unavailable,Mystiqueshapes Girls Ballet Tutu Neon Lime Green,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4,4.50

In [17]:
users['asin'] = users['asin'] + " "  # Add a space to the end of each asin string
all_asins = dict(users.groupby('reviewerID')['asin'].sum())  # add all the asin into one row 
users['asins'] = users['reviewerID'].map(all_asins) # create a new column for all asins to be grouped by reviewer

In [18]:
users['color'] = users['color'] + " "  # Add a space to the end of each color string
all_colors = dict(users.groupby('reviewerID')['color'].sum()) # add all colors together in one row per user 
users['colors'] = users['reviewerID'].map(all_colors)  # create a new column for all colors to be grouped by reviewer

In [19]:
users['name'] = users['name'] + " "  # Add a space to the end of each asin string
all_names = users.groupby('reviewerID')['name'].sum()  # add all names together in one row per user 
users['names'] = users['reviewerID'].map(all_names) # create a new column for all colors to be grouped by reviewer

In [20]:
users.head(3)

,reviewerID,asin,overall,color,name,Arts_Crafts_Sewing,Automotive,Baby_Products,Beauty_Personal_Care,Cell_Phones_Accessories,...,Wear_to_Work,Wrist_Watches,Arm_Warmers,Baseball_Caps,Berets,number_of_reviews,average_stars_given,asins,colors,names
0,A1KLRMWW2FWPL4,0000031887,5.0,unavailable,Mystiqueshapes Girls Ballet Tutu Neon Lime Green,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,3,5.00,0000031887 B000FH4JJQ B009H6NPBE,unavailable Black unavailable,Mystiqueshapes Girls Ballet Tutu Neon Lime Gre...
1,A2G5TCU2WDFZ65,0000031887,5.0,unavailable,Mystiqueshapes Girls Ballet Tutu Neon Lime Green,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,6,4.17,0000031887 B0019K9WDQ B005JJ2762 B005OZ9LB0 B0...,unavailable unavailable Black Black unavailabl...,Mystiqueshapes Girls Ballet Tutu Neon Lime Gre...
2,A1RLQXYNCMWRWN,0000031887,5.0,unavailable,Mystiqueshapes Girls Ballet Tutu Neon Lime Green,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,5,4.20,0000031887 B0007YVP1W B000LSWXWO B001GR05W4 B0...,unavailable Inspector missing missing missing,Mystiqueshapes Girls Ballet Tutu Neon Lime Gre...

Save to a csv to cluster in a separate notebook.

In [21]:
# pd.merge((users[['reviewerID', 'names', 'number_of_reviews', 
#                  'average_stars_given', 'asins', 'colors']].set_index('reviewerID')),  #merge newly engineered columns into one new DataFrame
#          users_cats, 
#          right_index=True,
#          left_index=True).drop_duplicates().to_csv('data/user_clustering.csv') # Drop duplicate rows

Add all columns with text together based on `asin` into new columns.

In [22]:
df['summary'] = df['summary'] + " "  # add a space to the end of the summary string
df['summary'].head()

0    Great tutu-  not cheaply made
1                      Very Cute!!
2         I have buy more than one
3                 Adorable, Sturdy
4          Grammy's Angels Love it
Name: summary, dtype: object

In [23]:
summary = dict(df.groupby('asin')['summary'].sum()) # add all review summaries together in one row per product 
df['one_sum'] = df['asin'].map(summary)  # create a new column for all the summaries 
df['one_sum'].head()

0    Great tutu-  not cheaply made Very Cute!! I ha...
1    Great tutu-  not cheaply made Very Cute!! I ha...
2    Great tutu-  not cheaply made Very Cute!! I ha...
3    Great tutu-  not cheaply made Very Cute!! I ha...
4    Great tutu-  not cheaply made Very Cute!! I ha...
Name: one_sum, dtype: object

In [24]:
df['reviewText'] = df['reviewText'] + " "    # add a space to the end of the reviewtext string
reviewText = dict(df.groupby('asin')['reviewText'].sum())   # add all review summaries together in one row per product
df['all_reviews'] = df['asin'].map(reviewText) # create a new column for all the review text 
df['all_reviews'].head()

0    This is a great tutu and at a really great pri...
1    This is a great tutu and at a really great pri...
2    This is a great tutu and at a really great pri...
3    This is a great tutu and at a really great pri...
4    This is a great tutu and at a really great pri...
Name: all_reviews, dtype: object

Create a new column for the average rating out of 5 stars for each `asin`.

In [25]:
overall_mean = dict(df.groupby(['asin']).mean().round(2)['overall'])
df['overall_mean'] = df['asin'].map(overall_mean)
df['overall_mean'].tail()

278637    4.6
278638    4.6
278639    4.6
278640    4.6
278641    4.6
Name: overall_mean, dtype: float64

Now that matching `asin` rows have the same values for summary and reviews and average overall score, we can drop all th duplicate asin rows.

In [26]:
df.drop_duplicates(subset='asin', inplace=True)

In [27]:
# Check shape to confirm rows were dropped 
df.shape

(13732, 826)

In [28]:
# Change types to string so that all rows are the same (some were integers before)
df['details'] = df['details'].astype(str)
df['description'] = df['description'].astype(str)

In [29]:
df['details'].value_counts().head()

0                                                                                                                                                                                                                                 8132
missing                                                                                                                                                                                                                           3869
Metal Factory,316L,Stainless steel,Cubic zirconia,channel,3 millimeters,Yes,Yes,Round brilliant,colorless,FL,ideal-cut,Simulated,Not treated                                                                                         6
BodySparkle Body Jewelry,Not stamped,Stainless steel,not-applicable,NA,NA                                                                                                                                                            4
Casio,FT500WC-5BVCF,FT-500WC-5BVCF,2014,Round,Mineral,Analog,Buckle,Resin,41 millimeters,11 millimeters,Nylon,8 inches,20 millimeters,Black,Beige,Stainless Steel,Stationary,Day,Luminous,27.22 Grams,Japanese Quartz,330 Feet       2
Name: details, dtype: int64

Create a feature interaction column with all the text added together. Decided not to include `details` just yet because it is very messy data and most cells were empty.  Will come back to it later if needed though.

In [30]:
df['all_text'] = df['all_reviews'] + " " + df['one_sum'] + " " + df['description']
df['all_text'].head()

0     This is a great tutu and at a really great pri...
23    The minute I saw this my heart skipped a beat....
29    Since learning a language from software is not...
42    If you really need to learn a new language, an...
58    We got this costume for my son to wear to Disn...
Name: all_text, dtype: object

Check the data types.

In [31]:
df.dtypes.head(15)

reviewerID             object
asin                   object
reviewText             object
overall               float64
summary                object
unixReviewTime          int64
review_date            object
color                  object
description            object
details                object
name                   object
size                   object
Arts_Crafts_Sewing    float64
Automotive            float64
Baby_Products         float64
dtype: object

Check value counts of size column

In [32]:
df['size'].value_counts().head()

missing                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        7278
Small                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           139
Medium                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          132
One SizeSize ChartP.when("jQuery", "cf").execute(function($){\n    \n});                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        128
SelectSmallMediumLargeX-LargeSelectif(typeof(TwisterNonJs) == 'undefined')\n\t\t    \t{\n\t\t\t\t\twindow.TwisterNonJs = {};\n\t\t\t\t\tTwisterNonJs.handleDropDown = [];\n\t\t    \t}\n\t\t\t\tTwisterNonJs.handleDropDown[0] = function(){\n\t\t\t\tvar twisterUpdateButton = "submit.twisterUpdateButton_0"\n\t\t\t\tdocument.getElementById("dummySubmitButton").setAttribute("name",twisterUpdateButton);\n\t\t\t\tdocument.forms['twister'].submit();\n\t\t\t\t};\n\t\t\t\tdocument.getElementById("native_dropdown_selected_size_name").onchange = function(){\n\t\t\t\t\tTwisterNonJs.handleDropDown[0]();\n\t\t\t\t};Size ChartP.when("jQuery", "cf").execute(function($){\n    \n});<input type="image" src="https://images-na.ssl-images-amazon.com/images/G/01/buttons/update-page._CB192192236_.gif" alt="Update Button" name="submit.twisterUpdateButton_0"/>     118
Name: size, dtype: int64

After reviewing size, I think it is not going to be helpful so I'll drop it.

In [33]:
df.drop(columns='size', inplace=True)

In [34]:
# Check remaining column names 
df.columns

Index(['reviewerID', 'asin', 'reviewText', 'overall', 'summary',
       'unixReviewTime', 'review_date', 'color', 'description', 'details',
       ...
       'Wallets', 'Wear_to_Work', 'Wrist_Watches', 'Arm_Warmers',
       'Baseball_Caps', 'Berets', 'one_sum', 'all_reviews', 'overall_mean',
       'all_text'],
      dtype='object', length=826)

In [35]:
# Check the shape after dropped column 
df.shape

(13732, 826)

In [36]:
df.head()

,reviewerID,asin,reviewText,overall,summary,unixReviewTime,review_date,color,description,details,...,Wallets,Wear_to_Work,Wrist_Watches,Arm_Warmers,Baseball_Caps,Berets,one_sum,all_reviews,overall_mean,all_text
0,A1KLRMWW2FWPL4,0000031887,This is a great tutu and at a really great pri...,5.0,Great tutu- not cheaply made,1297468800,2011-02-12,unavailable,This fits your . Make sure this fitsby ent...,0,...,0.0,0.0,0.0,0.0,0.0,0.0,Great tutu- not cheaply made Very Cute!! I ha...,This is a great tutu and at a really great pri...,4.61,This is a great tutu and at a really great pri...
23,A2WNN1DQVL4LH5,0123456479,The minute I saw this my heart skipped a beat....,5.0,Breathtaking 5 Stars,1383782400,2013-11-07,unavailable,This fits your . Make sure this fitsby ent...,0,...,0.0,0.0,0.0,0.0,0.0,0.0,Breathtaking 5 Stars VERY NICE Amazing so many...,The minute I saw this my heart skipped a beat....,4.17,The minute I saw this my heart skipped a beat....
29,A1F7YU6O5RU432,1608299953,Since learning a language from software is not...,5.0,"Suggest getting this 1 level at a time, so you...",1365465600,2013-04-09,unavailable,Access for up to 5 family members Download act...,0,...,0.0,0.0,0.0,0.0,0.0,0.0,"Suggest getting this 1 level at a time, so you...",Since learning a language from software is not...,4.31,Since learning a language from software is not...
42,A31ICLWQ9CSHRS,1617160377,"If you really need to learn a new language, an...",5.0,A real improvement over the last version!,1305936000,2011-05-21,unavailable,Access for up to 5 family members Download act...,0,...,0.0,0.0,0.0,0.0,0.0,0.0,A real improvement over the last version! Nice...,"If you really need to learn a new language, an...",4.62,"If you really need to learn a new language, an..."
58,A1059SSXUZZS1S,B00001W0KA,We got this costume for my son to wear to Disn...,4.0,"Great Costume, Awkward To Put On",1383696000,2013-11-06,Buzz Lightyear,Lead Free Child (4-6 & 7-8) Includes: Bodysuit...,0,...,0.0,0.0,0.0,0.0,0.0,0.0,"Great Costume, Awkward To Put On Perfectly fit...",We got this costume for my son to wear to Disn...,4.62,We got this costume for my son to wear to Disn...

Save changes to a csv called `category_only` and comment out the cell so it doesn't ever get overwritten on accident.

In [37]:
# df.drop(columns=['reviewerID','reviewText', 'overall', 'summary', 'unixReviewTime', 'review_date', 'color', 'description', 'details', 'all_text', 'one_sum', 'all_reviews']).to_csv('data/category_only.csv')

Start a new DataFrame with just the text columns.

In [38]:
df_text = df[['asin', 'name', 'color', 'details', 'description', 'all_text', 'one_sum', 'all_reviews']]

In [39]:
#Check the first 25 rows 
df_text.head(25)

,asin,name,color,details,description,all_text,one_sum,all_reviews
0,0000031887,Mystiqueshapes Girls Ballet Tutu Neon Lime Green,unavailable,0,This fits your . Make sure this fitsby ent...,This is a great tutu and at a really great pri...,Great tutu- not cheaply made Very Cute!! I ha...,This is a great tutu and at a really great pri...
23,0123456479,SHINING IMAGE HUGE PINK LEATHER JEWELRY BOX / ...,unavailable,0,This fits your . Make sure this fitsby ent...,The minute I saw this my heart skipped a beat....,Breathtaking 5 Stars VERY NICE Amazing so many...,The minute I saw this my heart skipped a beat....
29,1608299953,Learn French: Rosetta Stone French - Level 1,unavailable,0,Access for up to 5 family members Download act...,Since learning a language from software is not...,"Suggest getting this 1 level at a time, so you...",Since learning a language from software is not...
42,1617160377,Learn Italian: Rosetta Stone Italian - Level 1,unavailable,0,Access for up to 5 family members Download act...,"If you really need to learn a new language, an...",A real improvement over the last version! Nice...,"If you really need to learn a new language, an..."
58,B00001W0KA,Buzz Lightyear Boy's Deluxe Toy Story Costume,Buzz Lightyear,0,Lead Free Child (4-6 & 7-8) Includes: Bodysuit...,We got this costume for my son to wear to Disn...,"Great Costume, Awkward To Put On Perfectly fit...",We got this costume for my son to wear to Disn...
66,B00001WRHJ,Woody Deluxe Child - Size: Child S(4-6),unavailable,0,"5.5"" high 12"" wide Quality materials used to m...",My grandson has been a costume lover for the p...,Birthday gift 5year old Great for costume-lovi...,My grandson has been a costume lover for the p...
72,B00004SR8W,Lewis N. Clark Stash,Neck Stash,0,"Nylon Nylon lining Zipper closure 25.5"" should...",better quality than I expected for the price -...,Get this one it works. A bit too large for me ...,better quality than I expected for the price -...
84,B00004SR8Z,"Lewis N. Clark Deluxe Neck Stash, Beige",Beige,0,This fits your . Make sure this fitsby ent...,This pouch is lightweight and comfortable to w...,Would like it to be a bit longer Small but fun...,This pouch is lightweight and comfortable to w...
106,B00004SR9P,"Lewis N. Clark Add-A-Bag Travel Luggage Strap,...",Black,0,This fits your . Make sure this fitsby ent...,It's too short to be particularly useful. If i...,too short It Works! great product. Made handl...,It's too short to be particularly useful. If i...
122,B00004U1J2,Buzz Lightyear Jet Pack,One Size Child,0,"Polyester Imported 16"" high 12"" wide Quality m...",The Inflatable buzz lightyear costume jet pack...,"good Buzz Lightyear Jet Pack To Infinity, And ...",The Inflatable buzz lightyear costume jet pack...
135,B000051SEN,SUUNTO X-Lander Wrist-Top Computer Watch with ...,unavailable,0,This fits your . Make sure this fitsby ent...,I purchased my Suunto in 2005 (not from Amazon...,Purchased in 2005...STILL GOING STRONG!!!! Fav...,I purchased my Suunto in 2005 (not from Amazon...
143,B000051SEP,SUUNTO X-Lander Wrist-Top Computer Watch with ...,unavailable,0,This fits your . Make sure this fitsby ent...,I expected a lot more from a &#34;wrist comput...,Disappointed Among the Greatest Multi-Function...,I expected a lot more from a &#34;wrist comput...
149,B00005JHKE,Spider-Man Child Standard Costume,As Shown,0,Size: Child S(4-6). Spider-Man hood included. ...,This was for my grandson for Halloween and he ...,great Runs a bit small Guaranteed to Rip on Yo...,This was for my grandson for Halloween and he ...
154,B00005JSBK,Master Lock 1530DCM Locker Lock Combination Pa...,1 Pack,0,This fits your . Make sure this fitsby ent...,"Good lock, I use this for my gym locker and it...",good lock This is not your old high school loc...,"Good lock, I use this for my gym locker and it..."
159,B00005KJXN,Rubie's Costume Women's Nun Costume,Blackfrom24 sellersfrom1 seller,0,Polyester Imported 100% Polyester Complete cos...,"For the price, I think this is a fine costume....",Great for the cost! This was sent as a joke Nu...,"For the price, I think this is a fine costume...."
214,B0000643Q8,Skagen Men's 105LTX Titanium Grey Dial Watch,unavailable,"Skagen,105LTX,105LTX,Round,Mineral,Analog,Fold...",Quartz movement Mineral crystal Case diameter:...,"Great watch, extremely light, nice sinister me...",I love everything about the watch but why...? ...,"Great watch, extremely light, nice sinister me..."
219,B000067R84,Dora the Explorer Plush Backpack Bag,unavailable,0,This fits your . Make sure this fitsby ent...,"The baby loves his little Dora bag, but why th...",Grandson loves it! our little Dora fan loves h...,"The baby loves his little Dora bag, but why th..."
225,B00006I551,CASIO F91W-1 Casual Sport Watch,"4-Year Watch Protection Planfrom SquareTrade,W...","Casio,F-91W-1,F-91W-1,Square,Quartz,Analog,Buc...","Made in USA and Imported Micro Light, Hourly T...",Hard to beat the price but I didn't expect tha...,You get what you pay for F-91W New favorite wa...,Hard to beat the price but I didn't expect tha...
238,B00006XXGO,Converse Chuck Taylor All Star Core Ox,Natural White,0,100% Canvas Imported Rubber sole Shaft measure...,I wear my high-top chucks until they have hole...,"Exactly what I wanted. ""I like them and my bro...",I wear my high-top chucks until they have hole...
340,B000072UMJ,Converse Chuck Taylor All Star Low Top Sneakers,Navy,0,100% Textile Imported Rubber sole Shaft measur...,fits true to size i can wear this with anythin...,great shoes! She loved them!!! Fit her well Gr...,fits true to size i can wear this with anythin...
451,B000074RL3,Enell Women's High Impact Sports Bra,Black,0,Hook & Eye closure DESIGNED ESPECIALLY FOR WEL...,I have never been so lifted dependably in all ...,THE LADIES ARE HAPPY Long Lasting and Holds Up...,I have never been so lifted dependably in all ...
492,B000078CYM,AmeriBag Classic Healthy Back Bag tote Distres...,unavailable,0,Distressed Nylon SIZE: A compact daily bag spa...,I have used a version of this bag for many yea...,Classic Bag Still Works for Me Okay Great bag ...,I have used a version of this bag for many yea...
500,B00007AS82,Kipling Lancelot Flap Shoulder Bag,True Blue,0,"nylon flap closure 11"" high 9.5"" wide Water Re...","This bag is perfect for the new 10"" netbooks. ...","Perfect 10"" Netbook bag and messenger bag. Fli...","This bag is perfect for the new 10"" netbooks. ..."
505,B00007FFL9,PalmBeach Jewelry 14k Yellow Gold-Plated Open-...,Ring Size:6,"Palm Beach Jewelry,Not stamped,Gold-plated-bas...",Top Rated Seller - Trusted Since 1952 - 90 Day...,the ring is pretty but just a little to flashy...,the gold overlay is just a little to bright Pr...,the ring is pretty but just a little to flashy...
511,B00007GD8X,Buxton Women's Crossbody Mini-Bag,Black$22.18$20.75$25.26$19.73$23.90,0,"Leatherette Imported Flap closure 25"" shoulder...",Buxton doesn't seem to have the quality that i...,It's okay. Practical Perfect! Perfect little b...,Buxton doesn't seem to have the quality that i...

Compare what one cell of the new columns look like.

In [40]:
df_text['all_text'][0]

'This is a great tutu and at a really great price. It doesn\'t look cheap at all. I\'m so glad I looked on Amazon and found such an affordable tutu that isn\'t made poorly. A++ I bought this for my 4 yr old daughter for dance class, she wore it today for the first time and the teacher thought it was adorable. I bought this to go with a light blue long sleeve leotard and was happy the colors matched up great. Price was very good too since some of these go for over $15.00 dollars. What can I say... my daughters have it in orange, black, white and pink and I am thinking to buy for they the fuccia one. It is a very good way for exalt a dancer outfit: great colors, comfortable, looks great, easy to wear, durables and little girls love it. I think it is a great buy for costumer and play too. We bought several tutus at once, and they are got high reviews. Sturdy and seemingly well-made. The girls have been wearing them regularly, including out to play, and the tutus have stood up well. Fits the 3-yr old & the 5-yr old well. Clearly plenty of room to grow. Only con is that when the kids pull off the tutus, the waste band gets twisted, and an adult has to un-tangle. But this is not difficult. Thank you Halo Heaven great product for Little Girls.  My Great Grand Daughters Love these Tutu\'s.  Will buy more from this seller.  Made well and cute on the girls.  Thanks for a great product.NEVER BUY FROM DRESS UP DREAMS........I will buy more as long as I don\'t buy from &#34;Dress Up Dreams&#34;  I never rec\'d or order in FL. Only rec\'d pink, the purple one was missing.  Company is a rip off.  REFUSES to make good on purchase...... Real creeps. I received this today and I\'m not a fan of it but my daughter is I thought it would be puffier as it looks in the pic but it\'s not and the one they sent me is pink underneath and the waist band is pink which is not what I wanted due to the fact she already had the sandals she was gonna wear with it now I gotta find another pair of sandals,ima just keep it cuz she likes it. Bought this as a backup to the regular ballet outfit my daughter has to wear. So far, she\'s using it to play out her Cinderella dreams but I am sure we\'ll be able to use it for a recital sometime soon. The quality is just fine for the price we paid. I was not expecting a designer skirt for this price and got exactly what I paid for. Great tutu for a great price. It isn\'t a &#34;full&#34; or high quality skirt, but it is perfect for my daughter to wear over leggings for her little outfits. My daughter liked this, and it with her costume, but she would have liked it to be a bit fuller. For what I paid for two tutus is unbeatable anywhere!  I ordered a pink and turquios and they are vibrant and beautiful! The tutu is very full! Princess style! Not cheaply made! Not cheap materia! Obviously someone made these with love and care! I paid less than 7 bucks for a tutu I and I feel proud of my self for researching to the point of finding gold!Recommend 2-6 years!My daughter is two ! Wears size 4t and this skirt ( one size ) fit perfect and will probaly be able to accommodate her quickly growing waist for some time! Wonder my niece wears it every single day, yellow is her favorite color right now an this cute little tutu made he da. It is well built and we hope she gets lots of wear out of it. My daughter has worn this skirt almost every day since she received it and it\'s even been through the washer along with the other clothes.  It\'s amazing quality!  She fits a 4T and it\'s just above her knee, and has a little bit of growing room, although I\'m not so sure as much as others are saying.  But considering how often she wears it, I\'m not worried! ;) Purchased this tutu for my granddaughter\'s first birthday.  It fit nicely with room to grow in.  I\'m very please with it and will purchase more in varying colors in the future. Full and well stitched.  This tutu is a beautiful purple color that looks just like the picture.  It looks just adorable on our little fairy. This was a gift for a two year old and a five year old.  The girls squealed upon opening the box, they grabbed the tutus, put them on, and wore them the rest of the day.  The tutus seem to be well made, and can stand up to handling by little princesses.  I recommend these tutus. My 3yr old loved this tutu skirt in pink! Was hoping to order more in different colors.She had hardly used this,the stitching came apart in 2weeks.now it\'s lying in her closet..Altogether she wore it like 4-5 times for 20 mins or so.wish the stitching was of better quality to hold up while little ones wear it. Can\'t recommend. Perfect for my budding grand daughter ballerina! Beautiful vibrant color.  Fits great and easy to  clean!  I bought several more colors! Never GOT this item - but gave a 1 STAR because the replies from the SUPPLIER was GREAT.They tried to send the item more than once.My $ was refunded in a timely manner too.It was a shame I never got it for my daughter - it would of looked great with her OUTFIT for Dr. Seuss WEEK at school.Most original.Maybe next time. Nice and puffy tutu skirt. I would recommend this for girls under 10 yr. old.  It will be too short and small for older girls. Bought this for my niece as part of her fairy outfit.  She loves it and wears it all the time.  Well made for the price. My 4 year old daughter always wants to play dress up. I bought this for her for Christmas and she never wanted to take it off. It is almost a year later and she still has it!! It was well worth the money and has held up this long with nothing wrong with it!! I would recommend it Our granddaughters are all very girlie, so when the youngest one received this for Christmas, they all wanted it!  Great color and fit for a 2 year old as well as her aunt who is 30!  I would recommend this tutu for all little girls. Prompt delivery, and it is exactly as described.  The only reason I did not give it 5 stars is because I haven\'t washed it yet- so I don\'t know how it will hold up... Other than that my little girl LOVES her tutus (we got one in light pink also), especially spinning and running in them :)  She\'s on the little side, so my concern was that it would be too big, but the fit is perfect!  The elastic waist will expand with her as she grows.  Great tutu-  not cheaply made Very Cute!! I have buy more than one Adorable, Sturdy Grammy\'s Angels Love it It\'s ok Great for dress-up and for ballet practice Great value Good WOW !! ..is all I have to say! Wonderful and great shipping. Excellent quality! Wonderful tutu! Great Tutu Great tutu for little girls! Came apart in 2weeks! So cute! Never GOT IT.... Nice skirt must have for a fairy princess My daughter loved it Sassy! Practically Perfect in every way!  This fits your\xa0.     Make sure this fitsby entering your model number.    P.when("ReplacementPartsBulletLoader").execute(function(module){ module.initializeDPX(); }) Lime green Fit girls 2-10 years old Puffy skirt great for dance Trademarked By Mystiqueshapes'

In [41]:
df_text['one_sum'][0]

"Great tutu-  not cheaply made Very Cute!! I have buy more than one Adorable, Sturdy Grammy's Angels Love it It's ok Great for dress-up and for ballet practice Great value Good WOW !! ..is all I have to say! Wonderful and great shipping. Excellent quality! Wonderful tutu! Great Tutu Great tutu for little girls! Came apart in 2weeks! So cute! Never GOT IT.... Nice skirt must have for a fairy princess My daughter loved it Sassy! Practically Perfect in every way! "

In [42]:
df['description'][0]

'This fits your\xa0.     Make sure this fitsby entering your model number.    P.when("ReplacementPartsBulletLoader").execute(function(module){ module.initializeDPX(); }) Lime green Fit girls 2-10 years old Puffy skirt great for dance Trademarked By Mystiqueshapes'

Instantiate Tokenizer

In [43]:
tokenizer = RegexpTokenizer(r'\w+')

In [44]:
# Tokenize the color column for products df and make all words lowercase 
df_text['color'] = df_text['color'].apply(lambda x: tokenizer.tokenize(x.lower()))

/Users/rachelkoenig/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [45]:
# Check first few rows 
df_text['color'].head()

0         [unavailable]
23        [unavailable]
29        [unavailable]
42        [unavailable]
58    [buzz, lightyear]
Name: color, dtype: object

In [46]:
# Apply tokenize funtion to colors column for user df 
users['colors'] = users['colors'].apply(lambda x: tokenizer.tokenize(x.lower()))

In [47]:
users['colors'].head()

0                    [unavailable, black, unavailable]
1    [unavailable, unavailable, black, black, unava...
2    [unavailable, inspector, missing, missing, mis...
3    [unavailable, ballet, pink, missing, standard,...
4           [unavailable, white, missing, unavailable]
Name: colors, dtype: object

In [48]:
# Tokenize the all_text column and make all lowercase 
df_text['all_text'] = df_text['all_text'].apply(lambda x: tokenizer.tokenize(x.lower()))

/Users/rachelkoenig/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [52]:
# Check one cell 
df_text['all_text'][0][:20]

['this',
 'is',
 'a',
 'great',
 'tutu',
 'and',
 'at',
 'a',
 'really',
 'great',
 'price',
 'it',
 'doesn',
 't',
 'look',
 'cheap',
 'at',
 'all',
 'i',
 'm']

In [53]:
# Check value counts of name column
df_text['name'].value_counts().head(10)

Simple 6MM Gemstone Round Ball Stud Earrings For Women For Teen 925 Sterling Silver 9 Birthstones More Colors    6
Timex Ironman Classic 30 Mid-Size Watch                                                                          5
Birkenstock Women's Mayari Birko-Flor Sandal                                                                     5
Wrangler Men's Riggs Workwear Carpenter Jean                                                                     4
Simple 8MM Gemstone Round Ball Stud Earrings For Women For Teen 925 Sterling Silver 9 Birthstone More Colors     4
Hanes Ultimate Men's 4-Pack Boxer Brief                                                                          4
MG Low Profile Dyed Cotton Twill Cap                                                                             4
Allegra K Women's Off Shoulder Self Tie Bowknot Colorblock Casual Tunic Shirt                                    4
Hanes Men's Woven Plain-Weave Pajama Set                                                                         4
Birkenstock Women's Gizeh Thong Sandals                                                                          4
Name: name, dtype: int64

In [54]:
# Tokenize the name column and give it a new column, do not override it 
df_text['name_split'] = df_text['name'].apply(lambda x: tokenizer.tokenize(x.lower()))

/Users/rachelkoenig/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [55]:
# Compare the tokenized vs untokenized cells 
print(df_text['name'][0])

print(df_text['name_split'][0])

Mystiqueshapes Girls Ballet Tutu Neon Lime Green
['mystiqueshapes', 'girls', 'ballet', 'tutu', 'neon', 'lime', 'green']

In [56]:
# Tokenize name column for reviewers 
users['names'] = users['names'].apply(lambda x: tokenizer.tokenize(x.lower()))

Define a funtion to remove stop words

In [57]:
def remove_stopwords(text):
    words = [w for w in text if w not in stopwords.words('english')]
    return words

Apply the stop words function to the color & name columns.

In [62]:
df_text['color'] = df_text['color'].apply(lambda x : remove_stopwords(x))
df_text['color'].value_counts().head(10)

/Users/rachelkoenig/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

[missing]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       3135
[unavailable]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   2628
[black]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         1566
[white]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          357
[4, year, watch, protection, planfrom, squaretrade, covered, mechanical, electrical, failures, normal, use, 100, parts, laborget, fast, repairs, replacements, squaretrade, allstate, company24, 7, customer, support, free, shipping, repairs, deductibles, hidden, feescancel, anytime, full, refund, first, 30, days, fully, transferable, giftssquaretrade, protection, plans, valid, new, amazon, certified, refurbished, products, purchased, amazon, last, 30, days, purchasing, protection, plan, agree, protection, plan, terms, conditions, http, www, squaretrade, com, terms, standard, protection, plan, terms, conditions, delivered, via, email, within, 24, hours, purchase]     216
[brown]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          141
[ring, size]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     105
[navy]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           100
[red]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             81
[size]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            60
Name: color, dtype: int64

In [59]:
df_text['name_split'] = df_text['name_split'].apply(lambda x : remove_stopwords(x))

/Users/rachelkoenig/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

Instantiate lemmatizer & Create a function for lemmatizing

In [60]:
lemmatizer = WordNetLemmatizer()

def word_lemmatizer(text):
    lem_text = " ".join([lemmatizer.lemmatize(i) for i in text])
    return lem_text

Apply lemmatizer to name columns.

In [61]:
df_text['name_split'] = df_text['name_split'].apply(lambda x : word_lemmatizer(x))

/Users/rachelkoenig/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [63]:
users['names'] = users['names'].apply(word_lemmatizer)

In [64]:
# Check column names 
df_text.columns

Index(['asin', 'name', 'color', 'details', 'description', 'all_text',
       'one_sum', 'all_reviews', 'name_split'],
      dtype='object')

Read in color csv from [dataworld](https://data.world/dilumr/color-names/workspace/file?filename=wikipedia_color_names.csv)

In [65]:
colors = pd.read_csv('data/wikipedia_color_names.csv')

In [66]:
colors.head() # Check first 5 rows

,Name,Hex (24 bit),Red (8 bit),Green (8 bit),Blue (8 bit),Hue (degrees),HSL.S (%),"HSL.L (%), HSV.S (%), HSV.V (%)"
0,Absolute zero,#0048BA,0,72,186,217.0,100.0,37.0
1,Acid green,#B0BF1A,176,191,26,65.0,76.0,43.0
2,Aero,#7CB9E8,124,185,232,206.0,70.0,70.0
3,Aero blue,#C9FFE5,201,255,229,151.0,100.0,89.0
4,African violet,#B284BE,178,132,190,288.0,31.0,63.0

Turn the colors in the `Name` column into a list and make them all lowercase.

In [68]:
colors_list = list(colors['Name'])
[x.lower() for x in colors_list][:10]  # show only first 10 objects in the list

['absolute zero',
 'acid green',
 'aero',
 'aero blue',
 'african violet',
 'air force blue (raf)',
 'air force blue (usaf)',
 'air superiority blue',
 'alabama crimson',
 'alabaster']

In [69]:
# check the first 25 rows of the color column
df_text['color'].head(25)

0                                          [unavailable]
23                                         [unavailable]
29                                         [unavailable]
42                                         [unavailable]
58                                     [buzz, lightyear]
66                                         [unavailable]
72                                         [neck, stash]
84                                               [beige]
106                                              [black]
122                                   [one, size, child]
135                                        [unavailable]
143                                        [unavailable]
149                                              [shown]
154                                            [1, pack]
159                  [blackfrom24, sellersfrom1, seller]
214                                        [unavailable]
219                                        [unavailable]
225    [4, year, watch, protection, planfrom, squaret...
238                                     [natural, white]
340                                               [navy]
451                                              [black]
492                                        [unavailable]
500                                         [true, blue]
505                                      [ring, size, 6]
511      [black, 22, 18, 20, 75, 25, 26, 19, 73, 23, 90]
Name: color, dtype: object

Define a function to find only the words in a column that are also in the `colors_list`

In [70]:
def colors_only(words):
    colors = []   # instantiate an empty list 
    for i in [x.lower() for x in colors_list]:
        if i in words:
            colors.append(i)  # append the word to the the colors list if is in th colors_list 
    return colors  # return the list of words that are colors

In [71]:
# Test the function on a string 
colors_only('the sky blue table is flat')

['blue', 'sky blue']

Apply the colors only function to the name column of the product and users dfs

In [72]:
df_text['name_color'] = df_text['name_split'].apply(colors_only)

/Users/rachelkoenig/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [73]:
users['names_colors'] = users['names'].apply(colors_only)

Lemmatize product and user color columns and join list of words back together

In [74]:
df_text['color'] = df_text['color'].apply(lambda x: word_lemmatizer(x))

/Users/rachelkoenig/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [75]:
users['colors'] = users['colors'].apply(word_lemmatizer)

Apply colors_only function to the product and users color column

In [76]:
df_text['color'] = df_text['color'].apply(colors_only)

/Users/rachelkoenig/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [77]:
users['colors'] = users['colors'].apply(colors_only)

Compare the output of name and color columns.

In [79]:
df_text[['color', 'name_color']].head(25)

                         color           name_color
0                           []         [lime green]
23                          []               [pink]
29                          []  [french rose, rose]
42                          []               [rose]
58                          []                   []
66                          []                   []
72                          []                   []
84                     [beige]              [beige]
106                    [black]              [black]
122                         []                [jet]
135                         []                   []
143                         []                   []
149                         []                [tan]
154                         []                   []
159                    [black]                   []
214                         []                [tan]
219                         []                   []
225  [amazon, liver, red, tan]                   []
238                    [white]                   []
340                     [navy]                   []
451                    [black]                   []
492                         []              [taupe]
500          [blue, true blue]                   []
505                         []             [yellow]
511                    [black]                   []

Combine the color column with the colors extracted from the name column into on new feature called `colors_only`.

In [80]:
df_text['colors_only'] = df_text['color'] + df_text['name_color']

/Users/rachelkoenig/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [81]:
users['colors_only'] = users['colors']+ users['names_colors']

Save the tokenized names to a csv to use in the recommender model.

In [82]:
# df_text[['asin', 'name', 'name_split']].to_csv('data/names_to_vectorize.csv')

Check the output for a specific row.

In [83]:
df_text['colors_only'][0]

['lime green']

Generate set of colors (non repeated).

In [84]:
list_of_colors = {color for product in df_text['colors_only'] for color in product}

In [88]:
type(list_of_colors)

set

In [89]:
import time

Create new binary columns for each color represented in both the `users` df and product `df_text`.

In [90]:
# Begin timer.
t0 = time.time()
# Instantiate counter (for progress statement).
count = 0
# Iterate through list of colors.
for color in list_of_colors:
    # Print out progress statement.
    if count % 100 == 0:
        print("Completed " + str(count) + " out of " + str(len(list_of_colors)) + \
            " columns in " + str(round(time.time() - t0,4)) + " seconds.")
        
        
# Create column for each color.
# Each value is 1 if the user purchased something that color .
# Each value is 0 if the user did not purchase anything with that color in the description.        
    users[color] = [1 if color in users.loc[row, 'colors_only'] else 0 for row in users.index]
# Add one to counter (for progress statement).
    count += 1

# Code adapted from GA Instructor Matt Brems

Completed 0 out of 366 columns in 0.0002 seconds.
Completed 100 out of 366 columns in 207.0319 seconds.
Completed 200 out of 366 columns in 415.0321 seconds.
Completed 300 out of 366 columns in 621.4962 seconds.

Check an example to make sure it worked.

In [91]:
users['cornsilk'].value_counts()

0    168900
1        95
Name: cornsilk, dtype: int64

Save to a csv to use for clustering users.

In [92]:
#(users.set_index('reviewerID').iloc[:, -366:]).drop_duplicates().to_csv('data/user_colors.csv')

In [93]:
# Begin timer.
t0 = time.time()
# Instantiate counter (for progress statement).
count = 0
# Iterate through list of colors.
for color in list_of_colors:
    # Print out progress statement.
    if count % 100 == 0:
        print("Completed " + str(count) + " out of " + str(len(list_of_colors)) + \
            " columns in " + str(round(time.time() - t0,4)) + " seconds.")
        
        
# Create column for each color.
# Each value is 1 if the product is represented by that color .
# Each value is 0 if the product does not have that color in the description.        
    df_text[color] = [1 if color in df_text.loc[row, 'colors_only'] else 0 for row in df_text.index]
# Add one to counter (for progress statement).
    count += 1

# Code adapted from Matt Brems

Completed 0 out of 366 columns in 0.0002 seconds.

/Users/rachelkoenig/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()

Completed 100 out of 366 columns in 46.6203 seconds.
Completed 200 out of 366 columns in 94.7549 seconds.
Completed 300 out of 366 columns in 141.7924 seconds.

Check the output.

In [94]:
df_text.iloc[:10, -366:].sum()

raspberry rose     0
terra cotta        0
flame              0
sand dune          0
red                0
denim              0
nickel             0
ube                0
irresistible       0
pastel brown       0
navy               0
topaz              0
lime green         1
blue               0
olive              0
persimmon          0
bronze             0
heart gold         0
iceberg            0
pearl              0
bondi blue         0
rose gold          0
coral reef         0
smoke              0
tulip              0
blue lagoon        0
liver              0
dark taupe         0
spring green       0
boysenberry        0
                  ..
dirt               0
rose dust          0
wine               0
capri              0
mint               0
pink pearl         0
maize              0
citron             0
copper red         0
rose red           0
ua blue            0
columbia blue      0
ultramarine        0
copper             0
sangria            0
deep red           0
malachite          0
salmon             0
magenta            0
carmine            0
turquoise          0
titanium yellow    0
blueberry          0
rose quartz        0
pink lace          0
liberty            0
begonia            0
dark khaki         0
raspberry          0
tomato             0
Length: 366, dtype: int64

In [97]:
rosetta = df_text.loc[29].to_dict()

{k:v for k,v in rosetta.items() if v != 0}

{'asin': '1608299953',
 'name': 'Learn French: Rosetta Stone French - Level 1',
 'color': [],
 'details': '0',
 'description': 'Access for up to 5 family members Download activation key included Learn at your own pace with our course that never expires Proprietary speech-recognition technology compares your voice to a native speaker 100 times per second Access to award winning mobile app for 3-months - available on Kindle Fire HD, iOS, and Android Live online tutoring sessions with a Native Speaker - 3-month trial included Earbuds with microphone included in box',
 'all_text': ['since',
  'learning',
  'a',
  'language',
  'from',
  'software',
  'is',
  'not',
  'exactly',
  'the',
  'same',
  'as',
  'learning',
  'a',
  'language',
  'from',
  'going',
  'to',
  'live',
  'in',
  'the',
  'country',
  'itself',
  'i',
  'suggest',
  'picking',
  'up',
  'the',
  'rosetta',
  'stone',
  'software',
  '1',
  'level',
  'at',
  'a',
  'time',
  'like',
  'this',
  'french',
  'level',
  '1',
  'that',
  'way',
  'you',
  'know',
  'if',
  'you',
  'are',
  'able',
  'to',
  'learn',
  'from',
  'the',
  'software',
  'before',
  'investing',
  'even',
  'more',
  'money',
  'into',
  'it',
  'since',
  'total',
  'immersion',
  'into',
  'another',
  'country',
  'to',
  'learn',
  'is',
  'not',
  'always',
  'an',
  'option',
  'rosetta',
  'stone',
  'it',
  'the',
  'next',
  'best',
  'thing',
  'while',
  'a',
  'class',
  'environment',
  'might',
  'work',
  'better',
  'for',
  'some',
  'there',
  's',
  'not',
  'always',
  'time',
  'for',
  'that',
  'either',
  'sometimes',
  'there',
  's',
  'just',
  'enough',
  'time',
  'on',
  'the',
  'weekends',
  'or',
  'in',
  'the',
  'evenings',
  'after',
  'work',
  'to',
  'get',
  'a',
  'few',
  'hours',
  'of',
  'studying',
  'in',
  'or',
  'maybe',
  'you',
  'just',
  'don',
  't',
  'want',
  'to',
  'sit',
  'in',
  'a',
  'school',
  'like',
  'classroom',
  'trying',
  'to',
  'learn',
  'from',
  'an',
  'instructor',
  'that',
  's',
  'where',
  'rosetta',
  'stone',
  'comes',
  'in',
  'rosetta',
  'stone',
  'tries',
  'to',
  'be',
  'more',
  'than',
  'just',
  'a',
  'computer',
  'program',
  'instead',
  'it',
  's',
  'interactive',
  'and',
  'is',
  'a',
  'cross',
  'between',
  'software',
  'and',
  'an',
  'at',
  'home',
  'classroom',
  'spanish',
  'lesson',
  'the',
  'software',
  'comes',
  'with',
  'a',
  'headset',
  'and',
  'microphone',
  'so',
  'that',
  'while',
  'you',
  'are',
  'learning',
  'you',
  'also',
  'speak',
  'into',
  'the',
  'headset',
  'and',
  'respond',
  'to',
  'questions',
  'the',
  'software',
  'helps',
  'one',
  'learn',
  'how',
  'to',
  'pronounce',
  'the',
  'words',
  'and',
  'practice',
  'what',
  'you',
  've',
  'learned',
  'to',
  'help',
  'retain',
  'it',
  'unlike',
  'a',
  'classroom',
  'environment',
  'you',
  'can',
  'work',
  'at',
  'this',
  'at',
  'your',
  'own',
  'pace',
  'which',
  'i',
  'appreciate',
  'when',
  'i',
  'took',
  'a',
  'spanish',
  'class',
  'some',
  'of',
  'the',
  'students',
  'flew',
  'ahead',
  'of',
  'me',
  'while',
  'the',
  'rest',
  'of',
  'us',
  'were',
  'just',
  'trying',
  'to',
  'keep',
  'up',
  'rosetta',
  'stone',
  'lets',
  'a',
  'person',
  'learn',
  'at',
  'the',
  'pace',
  'they',
  'learn',
  'at',
  'fast',
  'or',
  'slow',
  'so',
  'they',
  'don',
  't',
  'end',
  'up',
  'missing',
  'anything',
  'along',
  'the',
  'way',
  'i',
  'm',
  'more',
  'comfortable',
  'learning',
  'from',
  'the',
  'program',
  'as',
  'well',
  'than',
  'in',
  'front',
  'of',
  'a',
  'group',
  'of',
  'strangers',
  'while',
  'going',
  'to',
  'france',
  'and',
  'living',
  'there',
  'for',
  'a',
  'while',
  'is',
  'probably',
  'the',
  'easiest',
  'and',
  'fastest',
  'way',
  'to',
  'learn',
  'french',
  'rosetta',
  'stone',
  'is',
  'the',
  'next',
  'best',
  'thing',
  'and',
  'a',
  'more',
  'realistic',
  'option',
  'for',
  'most',
  'people',
  'the',
  'product',
  'itself',
  'is',
  'five',
  'stars',
  'however',
  'the',
  'description',
  'is',
  'faulty',
  'i',
  'researched',
  'this',
  'product',
  'a',
  'great',
  'deal',
  'before',
  'purchasing',
  'and',
  'even',
  'got',
  'the',
  'free',
  'demo',
  'cd',
  'first',
  'i',
  'really',
  'do',
  'like',
  'the',
  'learning',
  'process',
  'it',
  'feels',
  'intuitive',
  'the',
  'problem',
  'is',
  'sitting',
  'at',
  'my',
  'desktop',
  'computer',
  'is',
  'inconvenient',
  'and',
  'i',
  'do',
  'not',
  'have',
  'a',
  'laptop',
  'so',
  'when',
  'i',
  'learned',
  'that',
  'there',
  'is',
  'an',
  'app',
  'for',
  'that',
  'i',
  'was',
  'thrilled',
  'i',
  'own',
  'both',
  'an',
  'iphone',
  'and',
  'an',
  'ipad',
  'so',
  'with',
  'the',
  'rosetta',
  'stone',
  'apps',
  'that',
  'link',
  'directly',
  'to',
  'my',
  'account',
  'i',
  'could',
  'learn',
  'and',
  'practice',
  'wherever',
  'i',
  'needed',
  'to',
  'for',
  'three',
  'months',
  'i',
  'made',
  'great',
  'progress',
  'whether',
  'at',
  'home',
  'in',
  'the',
  'backyard',
  'or',
  'at',
  'work',
  'on',
  'my',
  'lunch',
  'hour',
  'on',
  'day',
  '91',
  'i',
  'suddenly',
  'could',
  'not',
  'connect',
  'my',
  'apps',
  'kept',
  'saying',
  'no',
  'course',
  'found',
  'for',
  'this',
  'account',
  'the',
  'product',
  'still',
  'works',
  'on',
  'my',
  'desktop',
  'but',
  'it',
  'turns',
  'out',
  'the',
  'apps',
  'portion',
  'of',
  'the',
  'product',
  'was',
  'just',
  'a',
  'free',
  'trial',
  'if',
  'i',
  'want',
  'to',
  'continue',
  'learning',
  'this',
  'way',
  'i',
  'need',
  'to',
  'purchase',
  'a',
  'very',
  'expensive',
  'subscription',
  'no',
  'where',
  'on',
  'this',
  'product',
  'page',
  'does',
  'it',
  'say',
  'that',
  'the',
  'companion',
  'apps',
  'are',
  'a',
  'trial',
  'version',
  'i',
  'am',
  'very',
  'disappointed',
  'with',
  'rosetta',
  'stone',
  'and',
  'amazon',
  'i',
  'did',
  'call',
  'amazon',
  'but',
  'the',
  'rep',
  'i',
  'spoke',
  'to',
  'did',
  'not',
  'know',
  'whether',
  'the',
  'product',
  'info',
  'was',
  'written',
  'by',
  'rosetta',
  'stone',
  'or',
  'amazon',
  'i',
  'am',
  'sure',
  'it',
  'was',
  'the',
  'former',
  'amazon',
  'did',
  'try',
  'to',
  'assist',
  'me',
  'by',
  'offering',
  'a',
  'partial',
  'refund',
  'but',
  'that',
  'was',
  'not',
  'really',
  'what',
  'i',
  'wanted',
  'i',
  'want',
  'to',
  'continue',
  'to',
  'learn',
  'on',
  'my',
  'ipad',
  'my',
  'disappointed',
  'with',
  'amazon',
  'is',
  'because',
  'that',
  'call',
  'i',
  'made',
  'to',
  'them',
  'took',
  'place',
  'about',
  'two',
  'months',
  'ago',
  'and',
  'i',
  'see',
  'the',
  'product',
  'info',
  'page',
  'has',
  'not',
  'changed',
  'i',
  'do',
  'not',
  'see',
  'anything',
  'about',
  'the',
  'iphone',
  'apps',
  'being',
  'a',
  '90',
  'day',
  'trial',
  'update',
  'august',
  '23',
  '2013i',
  'see',
  'that',
  'amazon',
  'has',
  'updated',
  'the',
  'description',
  'slightly',
  'with',
  'this',
  'sentence',
  'enhance',
  'your',
  'learning',
  'on',
  'the',
  'go',
  'with',
  'rosetta',
  'stone',
  'mobile',
  'apps',
  'for',
  'the',
  'kindle',
  'fire',
  'hd',
  'ipad',
  'and',
  'iphone',
  'three',
  'month',
  'access',
  'included',
  'with',
  'purchase',
  'i',
  'personally',
  'think',
  'it',
  'is',
  'still',
  'obscure',
  'since',
  'the',
  'part',
  'about',
  'the',
  'mobile',
  'companion',
  'is',
  'much',
  'farther',
  'down',
  'in',
  'the',
  'description',
  'but',
  'at',
  'least',
  'it',
  'is',
  'something',
  'the',
  'first',
  'question',
  'was',
  'which',
  'computers',
  'to',
  'install',
  'this',
  'program',
  'rosetta',
  'stone',
  'has',
  'a',
  'two',
  'seat',
  'minimum',
  'i',
  'ended',
  'up',
  'putting',
  'the',
  '2nd',
  'installation',
  'on',
  'a',
  'laptop',
  'expecting',
  'to',
  'use',
  'the',
  'program',
  'in',
  'other',
  'locations',
  'however',
  'rosetta',
  'stone',
  's',
  'immersion',
  'method',
  'feels',
  'too',
  'intensive',
  'to',
  'me',
  'for',
  'use',
  'in',
  'most',
  'places',
  'away',
  'from',
  'home',
  'installation',
  'was',
  'easy',
  'enough',
  'even',
  'though',
  'the',
  'program',
  'got',
  'stuck',
  'a',
  'couple',
  'of',
  'times',
  'along',
  'the',
  'way',
  'the',
  'gear',
  'headset',
  'with',
  'microphone',
  'is',
  'sufficient',
  'pros',
  'for',
  'total',
  'immersion',
  'type',
  'instruction',
  'without',
  'the',
  'benefit',
  'of',
  'communicating',
  'with',
  'other',
  'people',
  'this',
  'seemed',
  'very',
  'good',
  'the',
  'voice',
  'recognition',
  'software',
  'is',
  'impressive',
  'i',
  'was',
  'able',
  'to',
  'immediately',
  'begin',
  'speaking',
  'and',
  'progressed',
  'to',
  'the',
  'second',
  'level',
  'of',
  'difficulty',
  'fairly',
  'quickly',
  'there',
  'are',
  'plenty',
  'of',
  'exercises',
  'and',
  'repetition',
  'and',
  'this',
  'will',
  'surely',
  'help',
  'in',
  'many',
  'ways',
  'including',
  'pronunciation',
  'there',
  'are',
  'learning',
  'sessions',
  'in',
  'this',
  'software',
  'to',
  'allow',
  'speaking',
  'with',
  'native',
  'french',
  'speakers',
  'for',
  'me',
  'as',
  'an',
  'individual',
  'this',
  'is',
  'a',
  'better',
  'way',
  'to',
  'learn',
  'than',
  'a',
  'formal',
  'classroom',
  'cons',
  'the',
  'limitation',
  'in',
  'the',
  'number',
  'of',
  'seats',
  '2',
  'this',
  'wasn',
  't',
  'a',
  'problem',
  'for',
  'me',
  'yet',
  'it',
  's',
  'something',
  'to',
  'know',
  'about',
  'lack',
  'of',
  'matching',
  'supplemental',
  'physical',
  'material',
  'such',
  'as',
  'index',
  'cards',
  'with',
  'conjugations',
  'and',
  'grammatical',
  'rules',
  'i',
  'feel',
  'the',
  'need',
  'for',
  'this',
  'and',
  'can',
  'source',
  'it',
  'out',
  'separately',
  'but',
  'again',
  'i',
  'prefer',
  'to',
  'learn',
  'outside',
  'a',
  'formal',
  'classroom',
  'lack',
  'of',
  'simple',
  'visuals',
  'to',
  'help',
  'with',
  'identifying',
  'grammatical',
  'patterns',
  'okay',
  'i',
  'admit',
  'it',
  'i',
  'm',
  'one',
  'of',
  'the',
  'millions',
  'of',
  'americans',
  'that',
  'massively',
  'struggles',
  'with',
  'any',
  'language',
  'either',
  'than',
  'english',
  'i',
  'have',
  'recently',
  'returned',
  'to',
  'college',
  'to',
  'finish',
  'out',
  'my',
  'bachelors',
  'the',
  'university',
  'i',
  'm',
  'enrolled',
  'in',
  'requires',
  'two',
  'years',
  'of',
  'a',
  'foreign',
  'language',
  'ugh',
  'kill',
  'me',
  'kill',
  'me',
  'now',
  'but',
  'with',
  'using',
  'rosetta',
  'i',
  ...],
 'one_sum': 'Suggest getting this 1 level at a time, so you know if you can learn from the program 4 stars BUT beware... Intense way to learn Helped me actually get an A in a foreign language class!! DO NOT BUY IF YOU EVER WANT TO RESELL IT. Rosetta Stone software is fun to use Great way to obtain functional conversation in a new language Great software, not so fun to install, and headset low quality A Neat System of Learning, A BIt Pricey Really nice refresher, unable to get microphone aspect to work Rosetta Stone - Excellent way to learn! Fun and effective Becoming Bilingual ',

Unfortunately this method of extracting color names from a string is not fool-proof.  It does over catch words and phrases that just have that word in them.  For example, Learn `French Rose`tta Stone, returns both French Rose and Rose as colors.  For the purposes of this project though, I decided to still use it because it it catches those "colors" in one product it'll catch them in another and most likely that means those products have the same words in the title and are therefore probably similar.

In [98]:
df_text.iloc[:5, :12]

,asin,name,color,details,description,all_text,one_sum,all_reviews,name_split,name_color,colors_only,raspberry rose
0,0000031887,Mystiqueshapes Girls Ballet Tutu Neon Lime Green,[],0,This fits your . Make sure this fitsby ent...,"[this, is, a, great, tutu, and, at, a, really,...",Great tutu- not cheaply made Very Cute!! I ha...,This is a great tutu and at a really great pri...,mystiqueshapes girl ballet tutu neon lime green,[lime green],[lime green],0
23,0123456479,SHINING IMAGE HUGE PINK LEATHER JEWELRY BOX / ...,[],0,This fits your . Make sure this fitsby ent...,"[the, minute, i, saw, this, my, heart, skipped...",Breathtaking 5 Stars VERY NICE Amazing so many...,The minute I saw this my heart skipped a beat....,shining image huge pink leather jewelry box ca...,[pink],[pink],0
29,1608299953,Learn French: Rosetta Stone French - Level 1,[],0,Access for up to 5 family members Download act...,"[since, learning, a, language, from, software,...","Suggest getting this 1 level at a time, so you...",Since learning a language from software is not...,learn french rosetta stone french level 1,"[french rose, rose]","[french rose, rose]",0
42,1617160377,Learn Italian: Rosetta Stone Italian - Level 1,[],0,Access for up to 5 family members Download act...,"[if, you, really, need, to, learn, a, new, lan...",A real improvement over the last version! Nice...,"If you really need to learn a new language, an...",learn italian rosetta stone italian level 1,[rose],[rose],0
58,B00001W0KA,Buzz Lightyear Boy's Deluxe Toy Story Costume,[],0,Lead Free Child (4-6 & 7-8) Includes: Bodysuit...,"[we, got, this, costume, for, my, son, to, wea...","Great Costume, Awkward To Put On Perfectly fit...",We got this costume for my son to wear to Disn...,buzz lightyear boy deluxe toy story costume,[],[],0

Save to a csv.

In [99]:
# df_text.drop(columns=['color', 'details', 'description', 'all_text', 
            #        'one_sum', 'all_reviews', 'name_color', 'name_split', 'colors_only']).to_csv('data/colors_split.csv')